name: Test and Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: "Username for Dockerhub Auth"
      DOCKERHUB_TOKEN:
        required: true
        description: "Token for Dockerhub Auth"


jobs:
  python:
    name: Python
    runs-on: ubuntu-22.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-actions@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm app sh -c "Tython manage.py wait_for_db && python manage.py test"
      - name: Python flake8  
        run: docker compose run --rm app sh -c "flake8"
        
          